import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdad5',
        'secondary-fixed': '#72fe88',
        'surface-container': '#eeedf3',
        'surface-container-low': '#f4f3f8',
        'surface-container-highest': '#e3e2e7',
        'on-error-container': '#93000a',
        outline: '#717786',
        'on-secondary': '#ffffff',
        secondary: '#006e28',
        'on-tertiary-fixed': '#410001',
        'on-tertiary-container': '#fffbff',
        'primary-fixed-dim': '#adc6ff',
        'on-surface-variant': '#414755',
        'surface-tint': '#005bc1',
        'primary-container': '#0070eb',
        'on-secondary-fixed': '#002107',
        surface: '#faf9fe',
        'surface-bright': '#faf9fe',
        'on-primary': '#ffffff',
        'tertiary-container': '#e2241f',
        'on-primary-container': '#fefcff',
        'on-tertiary': '#ffffff',
        'on-background': '#1a1b1f',
        'primary-fixed': '#d8e2ff',
        'inverse-surface': '#2f3034',
        'on-secondary-container': '#00732a',
        primary: '#0058bc',
        tertiary: '#bc000a',
        'on-primary-fixed-variant': '#004493',
        'on-secondary-fixed-variant': '#00531c',
        'inverse-primary': '#adc6ff',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001a41',
        'secondary-container': '#6ffb85',
        'surface-dim': '#dad9df',
        'secondary-fixed-dim': '#53e16f',
        'tertiary-fixed-dim': '#ffb4aa',
        'surface-container-high': '#e9e7ed',
        'surface-container-lowest': '#ffffff',
        background: '#faf9fe',
        'surface-variant': '#e3e2e7',
        'on-surface': '#1a1b1f',
        'outline-variant': '#c1c6d7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f1f0f5',
        'on-tertiary-fixed-variant': '#930005',
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0px 12px 32px rgba(26, 27, 31, 0.06)',
        'ambient-lg': '0px 24px 48px rgba(26, 27, 31, 0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
